### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sam3d** [raphael-cch/latex-tree#1]
No problem at all, just wanted to leave a thank you message for creating such an awesome plugin. Keep up the great work, gonna use this for all of my academic papers moving forward :)

**Comment by raphael-cch** [comment]
Glad that you find it helpful! Do let me know if you have any feature requests :)

**Comment by werunom** [comment]
Hey! Thanks for this package. I had a general question - in the snapshot you have given in the package mainpage, there is an indent from the second line in every section. How did you get that? That is a nice visual aid for knowing where the section starts and ends. Curious to know how to get make that happen...

Since it was a general question, didnt feel like opening another thread....

**Comment by raphael-cch** [comment]
@werunom The indent was the "Soft Wrap Hanging Indent" (in Settings > Editor). The indent was present only because the entire section is on a single line (look at the line numbers).

I am not aware of a way to display the entire section as indented without actually indenting and changing the file, but maybe some packages would be able to auto indent the entire file for you.

**Comment by werunom** [comment]
Tried it and I think its a nice feature. Thanks for pointing out that!
